### ISSUE TITLE
Segment file to use with GISTIC

### ISSUE THREAD

**Issue by alhafidzhamdan** [hartwigmedical/hmftools#103]
Dear Hartwig team,

I have run PURPLE and produced all the output files.
I want to now run GISTIC with your segment.tsv file.
However, I can't seem to find the correct column in that file - http://portals.broadinstitute.org/cgi-bin/cancer/publications/pub_paper.cgi?mode=view&paper_id=216&p=t

GISTIC wants

>     (1) Sample      (sample name)
>     (2) Chromosome      (chromosome number)
>     (3) Start Position      (segment start position, in bases)
>     (4) End Position      (segment end position, in bases)
>     (5) Num Markers      (number of markers in segment)
>     (6) Seg.CN      (log2() -1 of copy number)
> 

5 +6 are the columns that I can't find.

How can I generate the last two columns from the ${sample}.purple.segment.tsv file?

I have run GATK's CNV calling, TITAN, Sequenza, ABSOLUTE etc, but I have found PURPLE to be the most reliable and accurate estimate. Would be helpful if you could help me troubleshoot and prepare the segmentation file required by GISTIC ie "number of markers in segment", and log2()-1 of CN. 

Much appreciated!

A

**Comment by p-priestley** [comment]
Thanks for the nice feedback.

Not super familiar with GISTIC (as we wrote our own gene centric analysis to look for recurrent amps and dels), but based on the fields above you will need to  use the somatic output CNV file which is "TUMOR.purple.cnv.somatic.tsv"

This has sampleId, chromosome,start and end.  For seg.CN use the "copyNumber" field (you will need to convert to log2()).  I assume 'Num Markers' is used for confidence calculations.   For this I recommend "Depth Window Count".

The full copy number file description is here:

https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#copy-number-file

**Comment by amarinderthind** [comment]
@p-priestley I was also looking thing. It would be great if you can explain a bit, how gene-centric analysis calculate the significance of the recurrent amps and dels? And which one is the output file for those recurrent amps and dels with significance values if any?

**Comment by p-priestley** [comment]
Please take a look at section 19 of the supplementary information from our publication:

https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-019-1689-y/MediaObjects/41586_2019_1689_MOESM1_ESM.pdf

**Comment by DarioS** [comment]
Have you considered using [LINX](https://github.com/hartwigmedical/hmftools/tree/master/sv-linx#linkage-of-drivers-to-contributing-structural-variant-clusters)? It categorises the events (only if involving a driver gene from a pre-specified catalog) into groups such as GAIN_ARM, DEL, LOH_CHR, so you can differentiate between focal, arm-level, and chromosome-level events. GISTIC is created for microarrays and only uses change in fluorescence ratio / read depth ratio. LINX is a fancy version of it which is designed for DNA sequencing, so it can give single base resolution of where a copy number event starts and finishes. [GISTIC is described](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2011-12-4-r41)

> **Length-based Separation of Focal and Arm-level SCNAs**
> A major advantage of the ZD method is its ability to separate arm-level and focal SCNAs explicitly by length. 

They use a threshold of 98% of the arm length for focal events. LINX uses some complicated logic to be more accurate for WGS because it has much more information to help decide than microarray probe fluorescence intensities can ever provide. I wouldn't recommend using a computational method developed in 2011 for a data analysis in 2020 of a different biotechnology.

**Comment by amarinderthind** [comment]
> Please take a look at section 19 of the supplementary information from our publication:
> 
> https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-019-1689-y/MediaObjects/41586_2019_1689_MOESM1_ESM.pdf

Thanks you very much for this.

**Comment by alhafidzhamdan** [comment]
thanks @p-priestley for your suggestions! Will definitely troubleshoot.

thanks @DarioS for your suggestions also. I will GISTIC on my samples and compare the output with PCAWG (who also used GISTIC with WGS data). My plan is to always also run LINX next- currently running GRIDSS.
