### ISSUE TITLE
SAGE hg38 PoN filters

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#114]
Hi, 

Looking at SAGE hg38 PoN filtering recommendations, is it correct that you have the PON_COUNT threshold here lower for hotspots and panels? I'd expect the criteria to be less relaxed for hotspots. Unless the PON_MAX filter makes up for it.

https://github.com/hartwigmedical/hmftools/tree/master/sage#pon-filtering

```
bcftools filter -e 'PON_COUNT!="." && INFO/TIER="HOTSPOT" && PON_MAX>=5 && PON_COUNT >= 2' -s PON -m+ $annotated_vcf -O u | \
bcftools filter -e 'PON_COUNT!="." && INFO/TIER="PANEL" && PON_MAX>=5 && PON_COUNT >= 2' -s PON -m+ -O u | \
bcftools filter -e 'PON_COUNT!="." && INFO/TIER!="HOTSPOT" && INFO/TIER!="PANEL" && PON_COUNT >= 5' -s PON -m+ -O z -
```

**Comment by p-priestley** [comment]
Thanks for the feedback Vlad.

We have lowered these thresholds from GRCH37 simply because the PON we have created is from a much smaller set of samples (just 100 samples we have run so far compared to ~4000 in GRCH37).    We have tuned this to give similar results in 37 and 38 as best as possible and I checked all 'hotspots' that overlapped the PON.  There are

FYI - We compared 100 samples for all variant types between 37 and 38 and found the following results:

**SNV** - hg38 calls 1.5% more SNV.   ~2/3 (1%) of these were due to reduced PON filtering.    The new variants 

**MNV** - hg38 and hg19 produced near identical calls

**INDEL** - hg38 produces significantly more indels, but not due to PON filtering as more are also PON filtered.  Instead this is largely because we adopted the 3.3.2 GIAB NA12878 truthset bed file (3.2.2 file used in GRCH37)  as our 'HIGH CONFIDENCE' region.   HIGH_CONFIDENCE regions are called with more sensitivity than regions outside these variants.   3.3.2 includes many more microsatellite regions excluded from 3.2.2.   We found that the extra sensitivity was concentrated in these regions, and generally in samples with high microsatellite.   Our null tumor test (NA12878 vs self) produced minimal extra indels

**SV** - hg38 produces approximately 2% more SVs.  The PON appears to make little difference

**Comment by vladsaveliev** [comment]
Thanks so much Peter, this is very useful!

My question though was a little bit different.

For GRCh37, the hotspot threshold is 10, which is *higher* than the non-hotspot threshold 6:

```
bcftools filter -e 'PON_COUNT!="." && INFO/TIER="HOTSPOT" && PON_MAX>=5 && PON_COUNT >= 10' -s PON -m+ $annotated_vcf -O u | \
bcftools filter -e 'PON_COUNT!="." && INFO/TIER="PANEL" && PON_MAX>=5 && PON_COUNT >= 6' -s PON -m+ -O u | \
bcftools filter -e 'PON_COUNT!="." && INFO/TIER!="HOTSPOT" && INFO/TIER!="PANEL" && PON_COUNT >= 6' -s PON -m+ -O z -o $pon_filtered_vcf
```

For hg38, the hotspot threshold is 2, which is *lower* than the non-hotspot threshold 5:

```
bcftools filter -e 'PON_COUNT!="." && INFO/TIER="HOTSPOT" && PON_MAX>=5 && PON_COUNT >= 2' -s PON -m+ $annotated_vcf -O u | \
bcftools filter -e 'PON_COUNT!="." && INFO/TIER="PANEL" && PON_MAX>=5 && PON_COUNT >= 2' -s PON -m+ -O u | \
bcftools filter -e 'PON_COUNT!="." && INFO/TIER!="HOTSPOT" && INFO/TIER!="PANEL" && PON_COUNT >= 5' -s PON -m+ -O z -o $pon_filtered_vcf
```

I would have expected the hotspot threshold to be higher than the non-hotspot threshold for both GRCh37 and hg38 (even with the exact thresholds to be scaled down as you pointed).

Let me know if it makes sense! Just wanted to make sure there is no typo. In any case, can in my tests on a SEQCII benchmark the PoN improves the accuracy a lot!

Vlad

**Comment by p-priestley** [comment]
Sorry.  I get it now.   That does look wrong.   Just checking if that is what we actually ran to make the PON or if it wrong on the readme.

**Comment by jonbaber** [comment]
Hi Vlad, 

Thanks for pointing that out. That is indeed a typo.

I have fixed the readme.

Cheers, Jon

**Comment by vladsaveliev** [comment]
Thanks a lot!
