### ISSUE TITLE
LINX Errors Importing Known Fusions Resources CSV

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#115]
Almost all of the records cause an error message during import

```
14:31:05 - [ERROR] - file(databases/known_fusion_data.hg38.csv) invalid known-pair data: KNOWN_PAIR,RUNX1,RUNX1T1,AML,15156181,
14:31:05 - [ERROR] - file(databases/known_fusion_data.hg38.csv) invalid known-pair data: KNOWN_PAIR,RUNX1,USP42,AML,23877199,
14:31:05 - [ERROR] - file(databases/known_fusion_data.hg38.csv) invalid known-pair data: KNOWN_PAIR,SDC4,ROS1,Lung,25567305,
```

but - surprisingly - two of the pairs records are parsed successfully

```
14:31:05 - [INFO ] - loaded 2 known fusion gene-pairs from file: databases/known_fusion_data.hg38.csv
14:31:05 - [INFO ] - loaded known fusion data: KNOWN_PAIR(2), PROMISCUOUS_3(37), PROMISCUOUS_5(28)
```

**Comment by DarioS** [comment]
1.10

**Comment by alexiswl** [comment]
Hi DarioS, I've come across the same issue, even when using the hg19 version.   
I would recommend using the `hg19/dbs/knowledgebases/output/knownFusionPairs.csv` file inside [this tarball](https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FGRIDSS-Purple-Linx-Docker) as used in the [gridss-purple-linx](https://github.com/hartwigmedical/gridss-purple-linx) workflow

**Comment by alexiswl** [comment]
It's not reference specific as it's using just the names of the genes

**Comment by charlesshale** [comment]
The issue is that the old-format known fusion files are being loaded. Instead use the new known fusions file which is attached to the 1.10 Linx release.

So replace:
-fusion_pairs_csv ~/data/knownFusionPairs.csv 
-promiscuous_five_csv ~/data/knownPromiscuousFive.csv 
-promiscuous_three_csv ~/data/knownPromiscuousThree.csv

with:
-known_fusion_file ~/data/known_fusion_data.csv

thanks.
