### ISSUE TITLE
Germline SVs after somatic filtering

### ISSUE THREAD

**Issue by xtYao** [hartwigmedical/hmftools#128]
Hi

For a tumor/normal pair, I filter the VCF output from GRIDSS with GRIPSS to get the somatic variants and it works well. However, I am wondering if the "germline" variants in the normal sample is simply just `setdiff(GRIDSS, GRIPSS_SOMATIC)` or would the calls be different if I run GRIDSS with the normal BAM separately? Which way is recommended?

Thanks,
Xiaotong

**Comment by DarioS** [comment]
@d-cameron This one looks right up your alley. Perhaps it's time for it to make an appearance in the F.A.Q.

Xiaotong, assuming you derived a set of 'germline' / non-reference structural variants, what would you do with them? Say you have two groups of patients, Responder and Non-responder. How would you compare the groups fairly? A long time ago, I read about traditional SNP research and ancestry confounding is an important issue. That research community uses tools like [EIGENSTRAT and STRUCTURE](https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/cphg.48) Can structural variants data be computationally corrected for the common problem of _population stratification_? According to [Characterizing the Major Structural Variant Alleles of the Human Genome](https://www.cell.com/cell/fulltext/S0092-8674(18)31633-7), hg 38 has many rare structural variant alleles. Also, a better place for your issue would have been the [GRIDSS issue tracker](https://github.com/PapenfussLab/gridss/issues).

**Comment by p-priestley** [comment]
Hi Xiaotong,

I would say GRIDSS output = SOMATIC + GERMLINE + ARTEFACT

The artefacts will be a combination of sample specific artefacts (which will be unique to normal or tumor)  and recurrent artefacts (which may be shared between normal and tumor).     GRIPSS removes both germline and artefact, but to  find the germline variants you will need to apply filters.   This is still on the to do list for Hartwig but we are not planning on starting soon.   A good starting point is QUAL > 500 for germline variants.

Hope this helps.

**Comment by xtYao** [comment]
Thank Peter, Dario,

 

This is helpful. I’ll try the QUAL field filter. Also cross checking with other callers seems to help quite a bit.

 

Xiaotong

**Comment by DarioS** [comment]
Something else I have read is that different thresholds are typically used for breakend variants and breakpoint variants. You don't want to be using the QUAL fixed field (one of the first eight mandatory columns) but the sub-field named QUAL for the normal sample's genotype field. Choosing a suitable threshold seems hard.

**Comment by d-cameron** [comment]
Added the following to the GRIDSS FAQ:

### Should I do joint calling or run each sample individually?

**Joint calling should always be used for related samples** (e.g. tumour/normal or trio calling).
Joint calling will ensure that a common variant near the single-sample threshold of detection will be reliably reported as a shared variant.
This is not the case if the calling were done individually.
Note that this particular behaviour is not specific to GRIDSS and is common to all variant callers (hence the joint calling support in many callers).

Joint calling allows for sensivity detection of variants that are present subclonally (or at low coverage) that would not be detected if called individually.

GRIDSS performs joint assembly then reports a per-sample breakdown. Joint calling has higher coverage of shared variants thus resulting in more reliable assembly of that variant.

Determining whether two SV calls in two different VCFs are actually the same call is non-trivial.
Imprecise calls are especially problematic since the coordinates may differ between the VCF, or a call may be precise in one VCF and not in the other.
A good example of why reconciling SV calls is so problematic is the case where call A (chrX:1-99->chrY:1-99) overlaps call B (chrX:50-149->chrY:1-99), call B overlaps call C (chrX:100-199->chrY:1-99), but A does not overlap C at all. Joint calling obviates this step.
