### ISSUE TITLE
.jar file for code?

### ISSUE THREAD

**Issue by asoltis** [hartwigmedical/hmftools#13]
The README suggests there is a .jar file for this program, but I do not see this (break-point-inspector-x.y-with-dependencies.jar). Could you point to where this is?

**Comment by pdiakumis** [comment]
I have the same sort of question/wish: the break-point-inspector v1.5 jar file can be found in the Releases tab, over here:
https://github.com/hartwigmedical/hmftools/releases/download/bpi-v1-5/break-point-inspector-1.5-jar-with-dependencies.jar

But v1.5 was released in December, and there's been two new releases since without a jar file. So could we have an updated one please?

By the way, there's also a conda package of the same version on bioconda over here, if you prefer to work in conda: https://anaconda.org/bioconda/break-point-inspector
We can update that one once the new jar is released.

Cheers - Peter

**Comment by kduyvesteyn** [comment]
Sorry guys. Just made official releases for BPI v1.6 and BPI v1.7, you can find them (along with their jars) in the releases section.

In BPI v1.6 we added downsampling around regions with excessive coverage, and in BPI v1.7 we made that somewhat more aggressive. No real functional changes in these releases, and the downsampling has neglectible impact on the final output.
