### ISSUE TITLE
Aneuploidy Score

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#152]
[Aneuploidy Renders Cancer Cells Vulnerable to Mitotic Checkpoint Inhibition](https://www.nature.com/articles/s41586-020-03114-6), _Nature_, 2021 finds that an anuepolidy score can be calculated to determine samples which might be druggable by a spindle assembly checkpoint inhibitor. Could PURPLE output such a score as standard into the .purple.purity.tsv files? It should probably be calculated at base level rather than arm level, to prevent proportions more than 0.5, since I can see some samples have more than half of their arms being different ploidy from the basal ploidy in the .purple.purity.tsv file.

**Comment by p-priestley** [comment]
I read this paper earlier this week.   No intention to add a calculation at this stage although there should be sufficient information to do so yourself from the PURPLE output.    

In general, since aneuploidy may arise via different mechanisms, It is not immediately obvious how one should calculate an 'aneuploidy score'.    If you were to differ from the method in Cohen-Sharir et al paper then it may also affect the ranking of the samples and the validity of the conclusions.   My reading of the paper is that after controlling for WGD (and TP53 status which is also highly correlated with WGD) the correlation of aneuploidy and the dependencies on KIF18A and other essential genes in the Nature publication is not super strong (eg. see extended figures 10c and 10d), so I would like to see more evidence.
