### ISSUE TITLE
LINX Reciprocal Translocation Plot Doesn't Show Both Fusion Gene Models

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#161]
Could it automatically plot both derivative genes in the gene track?

![image](https://user-images.githubusercontent.com/631218/110259680-1292dc00-7ffd-11eb-9207-491a046e3ce2.png)

**Comment by p-priestley** [comment]
Linx will plot based on the -fusion path specified.     Only fusions LINX deems reportable will be added to the LNX_VIS_FUSIONS.tsv file by report

In this case FUS-TFCP2 is shown since FUS is a 5' promiscuous partner in the fusion knowledgebase file.   This is highly likely to be the pathogenic fusion in this

To draw the reverse, you would need to either manually edit the file OR add TFCP2_FUS to the knowledge base and rerun linx.
