### ISSUE TITLE
Description of PURPLE output files

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#17]
Sorry for bugging you again,

Are there any docs describing the PURPLE output files (apart from the README)? We've kept it pretty simple up to now, focusing on `purple.cnv` and `purple.gene.cnv`, and using only the obvious columns (chrom, start, end, gene, cn, mincn, maxcn). If there are no docs, could we get your comments on the following:

* How does `purple.gene.cnv` relate to `purple.cnv` (e.g. do you basically merge it with Ensembl transcript IDs or is it more complicated than that)?

* We often get negative Min/MaxCopynumber values, which also happens with the `purple.cnv` file. I'm not too sure how to interpret these values e.g. should we round to 0, is it a bug or something else?

* Trying to parse `purple.gene.cnv`: why does it have 30 column names, but only contains 29 fields per row? Up to now I've assumed that the first 6 columns are chr/start/end/gene/mincn/maxcn.

Many thanks - Peter

**Comment by jonbaber** [comment]
Hi Peter,

Unfortunately we don't have any documents explaining our output but always
happy to answer your questions:

   - Correct, just looking at the copy number at a gene level.
   - Yes, it is best you round to zero. Same as you may occasionally see
   bafs in very low purity samples > 1 (in which case you would round to 1).
   These are generally due to limitations in how we have inferred the value
   and indicate areas where we may need to improve our algorithms. We
   intentionally do not round it ourselves as we prefer to be transparent in
   our output.
   - The last column name was not real. I have removed it.

Also just a friendly reminder that purple can write directly to a database
as well. We have found this to be very helpful for facilitating analysis,
especially on a cohort level but even on a sample level as well. I would
encourage you to try it out if you haven't already :)

Cheers, Jonathan

**Comment by pdiakumis** [comment]
Thanks Jonathan, that's good to know about the CN values and the column parsing.
Been wanting to try out the db writing too; will give it a go soon.

Cheers - Peter
