### ISSUE TITLE
Comprehending CN segments from method STRUCTURAL_VARIANT

### ISSUE THREAD

**Issue by YY-SONG0718** [hartwigmedical/hmftools#187]
Dear author of hmftools,

I would like to ask about how to comprehend and analyze copy number (CN) segments in .purple.cnv.somatic.tsv result from purple ran with gridss SV input. 

From what I understand, these segments from method "STRUCTURAL_VARIANT" are those inferred from SVs and not from the canonical logR + BAF method for CN calculation. These segments are usually very short (<1000 bp) and have 0 BAF count. To be more specific, I am wondering:

1. How is total CN and minor allele CN calculated when there is no BAF count?
2. Many of these segments have length 0 and have a different CN with their neighbours, how is this possible, and what is the best way to comprehend these segments in downstream analysis?

Many thanks for your reply in advance.

With best wishes,
Yuyao Song

**Comment by p-priestley** [comment]
Hello Yuyao,

You are correct that short regions are inferred from the copy number of surrounding regions and the VAF of the flanking structural variants (https://github.com/hartwigmedical/hmftools/tree/master/purple#5-inferring-copy-number-for-regions-without-read-depth-information)

Allele specific copy numbers are also inferred from surrounding regions.    The method is described in detail here:
https://github.com/hartwigmedical/hmftools/tree/master/purple#6-allele-specific-copy-number-inferring

A segment with length 0 will be created if 2 structural variants are facing away from each other on consecutive bases with no bases lost in between.  We observe the copy number change here even though the length is 0 to ensure that every structural variant has an equivalent associated copy number change.    This may happen in practice a couple of scenarios.

1. A clean double stranded break with both ends repairing to other locations in the genome with no bases lost (eg. a reciprocal translocation)
2. When PUPRLE infers the existence of a breakend due to an inconsistent copy number change it is by convention placed at the exact base of the structural variant with inconsistent copy number change.  (https://github.com/hartwigmedical/hmftools/tree/master/purple#7-structural-variant-recovery)

Hope this is helpful

Peter

**Comment by YY-SONG0718** [comment]
Hi Peter,

Thank you very much for the clear and detailed info! This really helped us understand the result :)

We found that for SV inferred CN segments, they are sometimes shorter than 50 bp, which is the traditional length threshold of SVs. Since these segments can be found by one only Illumina sequencing read, we thought these are somewhat InDels but not the usual SVs we are looking for. 

We understand that it is the hmf pipeline's advantage to detect very small variants by combining several layers of variant calling. However, if there is a parameter that enables merging these very short segments with neighbouring segments? In this case, we can get SVs at least longer than an Illumina sequencing read and cause more obvious CN changes.

Thanks for your reply.

With best wishes,
Yuyao

**Comment by p-priestley** [comment]
There is no parameter.   If you want to remove short deletions and duplications less than 50 bases, you could filter these from your vcf prior to running PURPLE.   There will still be regions shorter than 50 bases though as part of reciprocal and complex events

Otherwise you need to smooth the output of PURPLE yourself.

**Comment by YY-SONG0718** [comment]
Sure, no problem. Thanks for your response!
