### ISSUE TITLE
GRIPSS filters out known viral insertions

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#190]
Using GRIDSS 2.12.0 (annotated with gridss_annotate_vcf_kraken2, gridss_annotate_vcf_kraken2) and latest versions of GRIPSS, AMBER, COBALT, PURPLE, and LINX, and I have also run VIRUSBreakend.
I am testing the pipeline's detection/annotation of genomic HBV insertion SVs using 11 HCC samples from the ICGC PCAWG, of which four have known HBV insertions (from 2-6 insertions per sample). Unexpectedly, the final output only contained one HBV insertion each in two of the samples, although the unfiltered/annotated GRIDSS VCF contained 19 HBV annotated breakends across the four samples with reported insertions.   From some parts of the GRIPSS code, it seemed like SVs annotated with viral insertions would be prioritized, so I thought that it may be related to the newer gridss_annotate_vcf_kraken2 annotation (which just fills the INSTAXID field in the VCF) leaving out a required field in the output.  Since the combined GRIDSS-PURPLE-LINX 1.3.2 pipeline's method using gridss.AnnotateInsertedSequence with a human_virus.fasta reference annotated the BEALN field, I added that annotation step to my pipeline and confirmed the annotations' presence, but the final VCF output from GRIPSS and PURPLE has not changed.
Is this expected behavior?

**Comment by p-priestley** [comment]
Hi Todd,

Sorry for the late reply.    We have shifted to using VirusBreakend fully for viruses, so they won't be handled any more in GRIPSS in any preferential or discriminatory manner.   So we won't fix this issue sorry.  

I think in general they will have been filtered due to minQual cutoffs (set to 1000 for SGL breakends).   You could set this lower possibly.

Peter
