### ISSUE TITLE
Using LINX with GRIDSS SV file

### ISSUE THREAD

**Issue by anitagh** [hartwigmedical/hmftools#192]
Is it possible to use LINX to just display structural variants generated by GRIDSS?

**Comment by sorjuela** [comment]
maybe similar question: can I run LINX only with GRIPSS output and not PURPLE?

**Comment by charlesshale** [comment]
When Linx generates a Circos plot for the SVs, it shows them in clusters and chains, and annotates driver events (eg AMPs and DELs) and LINE insertions. None of these annotations are possible without running Linx first to write the .vis files used to then make the plots.

Purple reads in the GRIDSS/GRIPPS SVs and shows them on a Circos plot without any of these annotations, so that could be used instead.

**Comment by charlesshale** [comment]
Linx currently requires Purple copy number data to work out junction copy number and LOH boundaries, which is then required for correct clustering and chaining. It also looks at segments of amplification and copy-number loss to attribute driver events to SVs and clusters. Purple also rescues otherwise filtered SVs to support copy-number changes. 

For germline SVs, Linx does not currently depend on Purple copy number data but currently this is not a first-class mode of operation.
