### ISSUE TITLE
Driver Catalog and HLA-C Deletions

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#193]
I notice one major difference between PURPLE version 2 and 3 results is that HLA-C no longer appears as a deletion for most samples. HLA-C is a highly polymorphic gene and has [6779 known alleles recorded in IMGT/HLA](https://www.ebi.ac.uk/ipd/imgt/hla/stats.html). Therefore, the human reference genome isn't a suitable sequence to align to. Was this a bug fixed recently? I can't find the details about it in the change log.

**Comment by p-priestley** [comment]
There is no recent change related to this.  HLA-C has never appeared as a DEL for us in 37.       

In Feb 2020 we regenerated the mappability file which is an input for COBALT for 38 as the initial version was generated incorrectly.   Could it be that you have updated this file when trialing the latest version?

**Comment by DarioS** [comment]
It might be, but unlikely. I generated driver catalogs on April 4 this year just before upgrading to version 3 and it had HLA-C in the .driver.catalog.tsv.

**Comment by p-priestley** [comment]
This is the only plausible explanation I can come up with.   Can you compare the mappability files used for the 2 runs directly?

**Comment by DarioS** [comment]
Thanks. Can you clarify what you mean by mappability file? I am only aware of specifying GC profiles to PURPLE. I just re-ran PURPLE version 2.47 and saw HLA-C again in output file CSCC_0006-M1.driver.catalog.tsv. Then, only changing `purple-2.47.jar` to `purple_v3.1.jar` (and `-hotspots` to `-somatic_hotspots`), I see an empty CSCC_0006-M1.driver.catalog.somatic.tsv, apart from the column headings (also empty for CSCC_0006-M1.driver.catalog.germline.tsv). It seems to me to be something else then.

**Comment by p-priestley** [comment]
I mean this file:    GC_profile.1000bp.38.cnp

It is used by COBALT, which then feeds into PURPLE

**Comment by DarioS** [comment]
The GC content file is from May 2020.

```bash
$ ls -lh databases/*cnp
-rw-r--r-- 1 ds6924 vt74 74M May 20  2020 GC_profile.hg38.1000bp.cnp
```

I created a new temporary directory and re-ran `cobalt` for one sample, output the files to the new directory and then I used `purple` with `-cobalt` input directory specifier changed to it. HLA-C is reported by PURPLE version 2.47 but not by version 3.1. I am now confident that the same version of cobalt and the GC content file have been used and the only difference is PURPLE version.

**Comment by p-priestley** [comment]
Sorry Dario.   I cannot explain, but if you attach the segment.tsv, gene.tsv and somatic.tsv output for chromosome 6 for both runs, I could probably get to the bottom of it.

**Comment by DarioS** [comment]
The files for comparison are in [comparePURPLEversions.zip](https://github.com/hartwigmedical/hmftools/files/6934771/comparePURPLEversions.zip) archive

**Comment by p-priestley** [comment]
Hi Dario,

HLA-C is determined to be lost in both v2.47 and v3 by PURPLE.   The root cause here of the deletions being found in HLA-C is likely that you are using an ALT genome which leads to HLA-C reads being mapped to alt contigs and causes PURPLE to find germline and somatic copy number loss in the region.   Can you confirm that you are using ALTs?       

The reason why the HLA-C is not reported in the driver catalog in  v2.48 is that we switched off recording of germline deletions in our driver catalog as it produces many false positives:

https://github.com/hartwigmedical/hmftools/commit/b0c1d034652d490602b751c871bf703d19228c51

Apologies if this missed the release notes.

Peter

**Comment by DarioS** [comment]
Good guess. Indeed, it is hg38 with alt contigs and also many HLA contigs as provided by Heng Li's (outdated) bwakit package.

```
    ...        ...
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
##contig=<ID=chrM,length=16569>
    ...        ...
##contig=<ID=chrUn_KI270302v1,length=2274>
##contig=<ID=chrUn_KI270304v1,length=2165>
##contig=<ID=chrUn_KI270303v1,length=1942>
    ...        ...
##contig=<ID=HLA-C*01:02:01,length=3349>
##contig=<ID=HLA-C*01:02:11,length=3057>
##contig=<ID=HLA-C*01:02:29,length=3349>
##contig=<ID=HLA-C*01:02:30,length=3333>
    ...        ...
```

So, it is not possible to accurately identify these variants in highly polymorphic regions like HLA and KIR? Have you thought of implementing an approach similar to [PolySolver](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4747795/) for PURPLE (copy number) and SAGE (SNVs) ? Basically, it infers the HLA alleles from the matched normal and does somatic variant calling of the matched tumour using the inferred alleles instead of chr6 reference.

**Comment by p-priestley** [comment]
Yes.  We have recently built a tool called Lilac which calls HLA types and determines allele specific copy number and allele specific RNA expression (https://github.com/hartwigmedical/hmftools/tree/master/lilac). I have not uploaded our documentation to the readme then, but I can provide to you if you are interested.   

It currently does not support genomes with  ALT contigs though.  We currently recommend to remap all the HLA alt contigs back to the NO_ALT genome first if you want to use Lilac.

SAGE also has special logic for HLA regions and does a good job generally (in our testing substantially better than polysolver), but again it does not currently support ALT contigs for HLA regions.

**Comment by DarioS** [comment]
Exciting developments! Other consortiums don't handle this scenario properly but Hartwig Medical Foundation does.

**Comment by alhafidzhamdan** [comment]
Hello @p-priestley @charlesshale ,

I saw your article on biorxiv on GIE and am interested in running it on our genomes.
First up, is there a plan in the near-term to enable LILAC to run with genomes aligned to hg38 with alt contigs? Just so that I can decide if we need proceed with doing realignment to the no alt version.

Second, following on from this, do we need to then also re-run PURPLE with the realigned BAM (to get cnv.gene.tsv file and somatic.vcf file from PURPLE)? 

Cheers

A

**Comment by p-priestley** [comment]
I can confirm that LILAC does not work well with the HLA alt contigs as the HLA reads are scattered across the ALT contigs rather than aligned to the 3 HLA class 1 genes.   

To make it work I would suggest you slice the 3 HLA genes and each of the HLA ALT contigs and then realign just those.     We have not built anything ourselves that does this yet and don't have a plan at this stage to do so.

**Comment by DarioS** [comment]
For alternate alignments, there is a post-processing tool called `bwa-postalt.js` which you're supposed to use to lift-over the alignments back to the main chromosomes, to make the BAM files compatible with existing software. However, we found that it doesn't work correctly and creating your own script would be necessary. Unfortunately, BWA appears to no longer be maintained.

**Comment by alhafidzhamdan** [comment]
Hi there,
Thanks for your feedback/suggestions.
I've now sliced the HLA loci and realigned to hg38 no alt genome, and took only the regions indicated in the bed file mentioned in #289
I created a script to that [here](https://git.ecdf.ed.ac.uk/mhamdan/fame_gbm/-/blob/master/submit_HLA_realignment.sh)
Please have a look and see if you think it looks OK.

I've run LILAC to completion now with no error. 
The script i ran is [here](https://git.ecdf.ed.ac.uk/mhamdan/fame_gbm/-/blob/master/submit_lilac.sh). Of note i used this pre-release version as per #289

I mostly got 3 output files ".candidates.coverage.csv", ".lilac.csv", ".lilac.qc.csv". 
And for the 1 sample that HLA small mutation was found, I got one additional ".lilac.somatic.vcf.gz" file.
Are these the expected output for LILAC? Of note I ran without RNA bams.

Now how do I call LOH and homozygous deletion based on the output files?
In the biorxiv paper you mentioned using minor/major allele CN cut-offs for LOH calling but I can't seem to find these annotations/columns in the output files.

Many thanks for your help! 

A

**Comment by p-priestley** [comment]
The output files are the expected ones.   I cannot vouch for your script as I have not done this myself, but if you have gathered together all the HLA class I contigs and remapped to the HLA-A, HLA-B and HLA-C, then in theory that should be correct.

The lilac.csv contains the allele specific copy number (assuming you passed in a copy number file generated by PUPRLE).  We treat allele CN < 0.5 as a deleted allele.   . Figure 1b in https://www.biorxiv.org/content/10.1101/2022.02.23.481444v1.full.pdf illustrates how to read the file.

Homozygous deletion is extremely rare (presumably because cells without any HLA presentation will likely be targeted by  NK cells) .  We do not have a single sample in our cohort with homozygous deletion of all 3 class I genes, but there are some cases with individual genes being homozygously deleted
