### ISSUE TITLE
recommended approach when "FAIL_SEGMENT" occurs

### ISSUE THREAD

**Issue by RichardCorbett** [hartwigmedical/hmftools#21]
Hi again,

I have a few samples (about 3 of 15) that are giving the FAIL_SEGMENT error.    When this error comes up are there any strategies that can be applied to still get a good result?   

thanks,
RIchard

**Comment by p-priestley** [comment]
Here is a description of FAIL_SEGMENT from: https://www.biorxiv.org/content/10.1101/415133v2.full

**FAIL_SEGMENT** - We remove samples with more than 120 copy number segments unsupported
at either end by SV breakpoints. This step was added to remove samples with extreme GC bias,
with differences in depth of up to or in excess of 10x between high and low GC regions. GC
normalisation is unreliable when the corrections are so extreme so we filter.

This affects approximately 1-2% of our samples and we fail these samples internally for our patient reporting and analysis as we are concerned that we may miscall deletions or amplifications or have poor sensitivity in high GC regions.   We find it is also often associated with calling many false positive short inversion SV in our sv calling, presumably due to related DNA damage.  

In other datasets and in some of our early sample batches we have seen this happen much more frequently.   It certainly does not need to be a hard fail and depends on how you want to use the sample, but is an indication of lower quality  DNA.
