### ISSUE TITLE
PURPLE Gene Copy Number for TCRA or TRA Gene

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#212]
It was recently [published in _Nature_](https://www.nature.com/articles/s41586-021-03894-5) that it is possible to estimate T cell fraction directly using genomics data without needing RNA-seq for cell type deconvolution using a reference database. I can't find TCRA or TRA (current official name) in the PURPLE gene copy output. I got the hg38 coordinates which [TcellExTRECT](https://github.com/McGranahanLab/TcellExTRECT) uses and overlapped them with the genomic ranges in the gene CNV output file. None of the genes look relevant.

```
      chromosome    start      end      gene
16374      chr14 21633836 21634940    OR10G2
16375      chr14 21665083 21666024     OR4E2
16376      chr14 22096507 22096608     TRDV1
16377      chr14 22556311 22557062 LINC02332
16378      chr14 22564905 22589269      DAD1
16379      chr14 22598237 22613215     ABHD4
16380      chr14 22633768 22634811     OR6J1
```

I am seeking this because one of the steps, `adjustTcellExTRECT`, asks the user to provide purity and TCRA copy number. Also, I wonder if the underlying concept could be incorporated into PURPLE's standard purity and ploidy file. Useful for cancer-oriented analysis.

**Comment by p-priestley** [comment]
Hi Dario.   

The genes annotated in our gene copy number file were selected a few years ago based on some criteria which were probably a bit sub-optimal.  However we actually happen to be working on updating our gene an transcript annotations to best practice right now.  We expect to upgrade to this within 1 month.

This is the high level plan for the new model:

1. HMF’s gene model is keyed on HGNC symbol (referred to as “gene” in our data model)
2. HMF’s universe of genes consists of all HGNC symbols (http://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt) that are matched to an ensembl gene id  that also exists in the latest ensembl version, or failing that gene with matching HGNC symbol in Ensembl,,
3. HMF’s universe of transcripts consists of all ensembl transcripts belonging to a gene with a matching HGNC symbol
4. HMF uses the ensembl canonical transcript as its canonical transcript.   Functional annotations of point mutations are made relative to this transcript, drivers are called on this transcript, and the transcript is favored in fusion prioritisation.  Specific additional transcripts of clinical interest (eg. CDKN2Ap14ARF) may be configured for specific genes in the driver gene panel and will be also used to call drivers in this gene.

I just checked HGNC and all the TRA V and J genes will be included in this update.   

In the meantime you can just select that region from the somatic CNV file.   I am not sure the resolution required by that tool, but I can imagine that you likely want to use the segment.tsv file as input instead of the smoothed PURPLE output.   

Peter
