### ISSUE TITLE
Linx compatability

### ISSUE THREAD

**Issue by dominikglodzikhms** [hartwigmedical/hmftools#224]
Hello there,

Thank you for the fantastic work in putting together the software suite.

I wondered if Linx could be used on top of the combination of Purple CNV profile and  structural variants from Manta (instead of Gridss) written to a .vcf file.
What are required fields in the structural variant .vcf file that Linx requires?

Best wishes
Dominik

**Comment by p-priestley** [comment]
Hi Dominik,   we were discussing this briefly today.     We previously used Manta, but have not done so for nearly 3 years now, and LINX was built after that so we are not sure what will not work.   The most important field in the VCF is "TAF" - ie tumor allelic frequency, but we are not 100% sure what else might break since Manta and GRIDSS have different variant representations.   

We don't have any PURPLE output based on Manta SV inputs.   Would you be able to provide a mini vcf with a few sample variants which we can try out and advise you on?

You can post here or share privately if you like at p.priestley@hartwigmedicalfoundation.nl
