### ISSUE TITLE
Comments/notes on PURPLE 3.2

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#240]
I realize that it is probably not exactly meant for public consumption, but just to see how it would work, I tried running Purple 3.2 yesterday.

Just a couple of notes:
1) Previous use of ref_genome_version HG38 had Purple 3.1 log "Using ref genome: V38", but Purple 3.2 reported "Using ref genome: V37" and then Purple crashed when at "Generating driver catalog"; I assume mismatch of data for chromosomes with/without leading "chr".  Using "38" instead of "HG38" fixed that issue.
2) The previous variant effect summaries SEC and SEW from the SnpEff annotation were no longer present and replaced by IMPACT summary.  I was going to extract the field out of IMPACT in the vcf, but it looks like it did not contain the full effect from the SnpEff annotation, as when I examined missense or nonsense variants, it was only listing the nucleotide impact, but after that just reported ",..." ; it did not include what I think should have been transcript and/or protein impacts.

**Comment by charlesshale** [comment]
I just ran Purple 3.2 passing in -ref_genome_version HG38 and it correctly set the version to v38. The valid values are '38', 'V38' and 'HG38', as per https://github.com/hartwigmedical/hmftools/blob/master/hmf-common/src/main/java/com/hartwig/hmftools/common/genome/refgenome/RefGenomeVersion.java. So not sure why it didn't accept that same value for you.

We are now using Pave (https://github.com/hartwigmedical/hmftools/tree/master/pave) instead of SnpEff for gene impact annotations, but Purple can still process the SnpEff annotations. 

Yes the 'Impact' entry replaces SEW and SEC, and it has dropped WorstCodingTranscript and WorstCodingEffects and added SpliceRegion and OtherReportableTranscripts. It previously did not contain every SnpEff field, only a subset. See https://github.com/hartwigmedical/hmftools/tree/master/hmf-common/src/main/java/com/hartwig/hmftools/common/variant/impact for details.
