### ISSUE TITLE
log4j security issue

### ISSUE THREAD

**Issue by tomvdbosch** [hartwigmedical/hmftools#244]
Hi, 

According to my IT department, there is a security risk if I have software that uses old versions of apache log4j on my computer. According to a scan tool, Cobalt, Amber, Gripss and Purple contain old versions of log4j as shown in the attached image. Is there any way it would be possible to update this, or could someone with more knowledge on cyber security tell me if there is an actual risk with using HMFtools? I have removed them from my pc for now per request of the IT department, but would like to use these tools again in the future.
The versions I use are the latest ones from the download links.

![image](https://user-images.githubusercontent.com/67101906/147816661-68855a8e-9010-4bfe-95b9-81b7d80ba2cf.png)

**Comment by charlesshale** [comment]
We consider the risk low because these programs do not interact with network messaging nor typically external public data. There would have to be malicious content inserted into a BAM, VCF or reference data file, which the programs would then need to log to expose the security flaw.

However we are in the process of making releases of each of the above over the next few weeks.

The Gripss 2.0 and Linx 1.17 releases were made with the fixed logging library.
