### ISSUE TITLE
PURPLE support for non-GRCh37/GRCh38?

### ISSUE THREAD

**Issue by chunlinxiao** [hartwigmedical/hmftools#256]
Looks like PURPLE only support GRCh37/38 based analysis - is there a way to support non-GRCh37/38 reference?

i.e.. providing scripts to generate required input files etc.

**Comment by p-priestley** [comment]
We do not support other reference genomes unfortunately. 

There are a number of ref genome specific assumptions in PURPLE and the input components (AMBER and COBALT).   These include a GC_profile, mappability masking, common SNP locations for BAF measurement), chromosome names, centromere locations and telomere lengths.        Some are inputs and could be generated, but some are hardcoded unfortunately.

**Comment by jamesdalg** [comment]
If I wanted to take the long task of making a pull request to make PURPLE work for a nonhuman species (e.g. mouse), what code would need to be rewritten to allow for a third or custom genome option? The way to make the other files seems straightforward. I see RefGenomeCoordinates.java  and RefGenomeVersion.java to be good starting points for modification. If I might ask a difficult question, what other files would need to be modified before building and compiling? I definitely realize that this might be a bit more involved, but it could yield insights we don't currently have as there are experimental perturbations that aren't possible to do otherwise.

**Comment by p-priestley** [comment]
This sounds like a big job.   

Below an overview of what I can think of functionally that depends on the genome:

Mandatory Config files - these files would need to be generated for the mouse genome
- Heterozygous points (used by amber)
- GC_profile.1000bp  (used by cobalt and purple - used to define GC and mappability / 1kb)
- Ensembl cache (used by purple)

Internal issues (may not be exhaustive)
- Chromosome 1-22, X,Y are configured explicitly in code (I understand mouse genome has chr1-19,X,Y)
- Chromosome lengths are hard coded for 37, 38
- Centromere locations are hard coded for 37,38
- short arms of certain chromosomes have special treatment
- PURPLE handles certain known common human germline aberrations on specific chromosomes (eg. trisomy)

Optional gene related config (not an issue if you don't want to run drivers)
- Hotspots
- driver gene panel

**Comment by jamesdalg** [comment]
From looking at this, it seems easy enough to make CHM13 (the new T2T genome) work. I'd only have to change the lengths of chromosomes internally.

**Comment by jamesdalg** [comment]
I've begun work on CHM13v2 and finished work on amber and generated a CHM13 amber jar. I'll work on cobalt, purple, and gripss in the next week or so. Feel free to look at what I've done here: https://github.com/jamesdalg/hmftools
I should be making a pull request in a few days, once I've tested everything.

**Comment by Se-Jung-LEE** [comment]
Hello,

I have read both of your posts with great interest.

I would like to ask if it is now possible to apply other versions of reference genomes, such as CHM13.

Thank you.

**Comment by p-priestley** [comment]
We support 37 and 38 only sorry. I am not sure how James's explorations went.
