### ISSUE TITLE
Documentation: Meaning of INF SV type

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#260]
Taking documentation from https://github.com/hartwigmedical/hmftools/blob/942b5080ff412d088c9559b05b55e4d1e03109c4/linx/src/main/java/com/hartwig/hmftools/linx/types/ResolvedType.java, 
what precisely is the meaning of the INF simple type? The rest seem somewhat obvious:
 DEL, -deletion
    DUP, -duplication
    INF, **<unsure of this meaning>**
    SGL, -"single breakend SV support" (https://github.com/hartwigmedical/hmftools/tree/master/purple)
    INV, -Inversion
    INS, -Insertion
    UNBAL_TRANS, -unbalanced translocation
    SIMPLE_GRP, // group of DUPs, INS and DELs - always dissolved in final classification

**Comment by p-priestley** [comment]
INF = inferred breakend (by PURPLE) to explain a copy number transition not explained by a SV.   I updated PURPLE documentaiton slightly to explain it:
https://github.com/hartwigmedical/hmftools/blob/master/purple/README.md#7-structural-variant-recovery

**Comment by amarinderthind** [comment]
What is Pair.Other SV?

**Comment by p-priestley** [comment]
PAIR_OTHER is any 2 variant cluster which is does not fall into one of our defined categories and is considered INCOMPLETE as given their orientation  they do not make a consistent chromosome.  This may occur due to FP vairant calls, missed variant calls or under clustering of more complex structures.
