### ISSUE TITLE
PURPLE and chrY copy number values in tumors with matched non-tumor samples with chrY loss

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#276]
This was run using PURPLE 3.1.  I looked through change logs for the versions released since then, but I do not see changes that I would expect to impact this issue.

I have used the PURPLE somatic CN output file purple.cnv.somatic to calculate which samples have chrY loss.  Basically, if length of segments with copyNumber<0.5 is greater than 50% of the total segments on chrY, then call it.a loss.
For most samples, those results looked reasonable when looking at PURPLE's input.png and circos.png CIRCOS plot, but I noticed a few discrepant samples.  Reviewing the cnv.somatic and purple.segment.tsv data, most samples had ~9.5k chrY depthWindows, but those discrepant male samples had much lower number of depthWindows (approx. 250, 2700, 4100). In reviewing the input.png CIRCOS, the matched non-tumor reference samples for those tumors have some proportion of chrY loss (which is known to occur in "normal" tissue).  Because of that, it appears that PURPLE is calling the germlineStatus of many of the chrY somatic call segments in those samples as "HET_DELETION" and not counting them when summarizing chrY CN levels.

**Comment by p-priestley** [comment]
Hi Todd.  

We have not really dealt with mosaic Y loss in our tools (mainly as we have no actionable genes on the Y chromosome) but you raise a good point.     I propose to handle this similar to other germline aberrations (https://github.com/hartwigmedical/hmftools/tree/master/cobalt#cobalt), specifically mosaic X.   Marking the chr Y regions as  HET_DELETION also feels wrong since there is only 1 copy soon.

I will put this on our backlog as an improvement to add next time we touch this topic.    

Peter
