### ISSUE TITLE
Conda versions are not up to date

### ISSUE THREAD

**Issue by Kdreval** [hartwigmedical/hmftools#281]
Hi!
Thank you for developing this very comprehensive set of tools!

I mentioned that the tools available through conda are not up-to-date with latest releases. For example, the latest version of SAGE available through conda is 2.8 (https://anaconda.org/bioconda/hmftools-sage), but the version 3.0 has been released already. The same applies to the other tools.

Is this something you are maintaining yourself? Are you planning to update conda builds to make latest versions available for use?

Would appreciate updates on this.

Thanks!

**Comment by pdiakumis** [comment]
Hi @Kdreval,
I'll try and submit pull requests to bioconda to update those later today. We rely on the awesome bioconda community to maintain those - see e.g. the history in <https://github.com/bioconda/bioconda-recipes/tree/master/recipes/hmftools-sage>.

**Comment by pdiakumis** [comment]
I think the reason the SAGE 3.0 update wasn't picked up by bioconda is because the jar file in the [release page](https://github.com/hartwigmedical/hmftools/releases/tag/sage-v3.0) has a different pattern to the usual `sage-{{ version }}.jar`, i.e. `sage_v3.0.1.jar` instead of `sage-3.0.jar`. 

@charlesshale fyi if you could keep those jar patterns in mind for next time because we track those in the conda recipes e.g. [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hmftools-sage/meta.yaml#L9). And these get used by a lot of folks as you can see from e.g. the [sage file downloads page](https://anaconda.org/bioconda/hmftools-sage/files).
There's also an inconsistency with 3.0 release vs. 3.0.1 jar for SAGE from what I can see.

The recent LINX 1.19 update was also not picked up for the same reason, since the [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hmftools-linx/meta.yaml#L8) expects a different jar pattern. Those patterns keep on getting changed to match what you have in the releases, so it would be great to stick to e.g. `https://github.com/hartwigmedical/hmftools/releases/download/tool-v{{ version }}/tool-{{version}}.jar` as much as possible to get them built automatically from the bioconda side (and to stop bothering you folks here :-)).

Re: the rest of the conda packages, there are currently automated PRs for [cobalt 1.13](https://github.com/bioconda/bioconda-recipes/pull/34435) and [amber 3.9](https://github.com/bioconda/bioconda-recipes/pull/34434) which have some issues that I think might be related to the infra used by bioconda over the weekend, and not hmftools.

I'll follow up tomorrow with more, and push through for LINX and SAGE updates as is for now.

**Comment by pdiakumis** [comment]
Opened new PRs for:

- [amber 3.9](https://github.com/bioconda/bioconda-recipes/pull/34492)
- [cobalt 1.13](https://github.com/bioconda/bioconda-recipes/pull/34491)
- [isofox 1.4](https://github.com/bioconda/bioconda-recipes/pull/34493)
- [linx 1.19](https://github.com/bioconda/bioconda-recipes/pull/34487)
- [sage 3.0.1](https://github.com/bioconda/bioconda-recipes/pull/34490)

Hopefully should all be merged within a day or two.

**Comment by Kdreval** [comment]
Great, thank you so much! Very much appreciate your time working on it!

**Comment by pdiakumis** [comment]
All bar isofox should be installable now (that one will take a few more hours probably).

```
mamba create -n hmf
conda activate hmf
mamba install -c conda-forge -c bioconda \
  hmftools-linx \
  hmftools-amber \
  hmftools-cobalt \
  hmftools-sage
```

**Comment by Kdreval** [comment]
Thanks @pdiakumis ! I can confirm I had successfully installed and run the new version. Amazing speed with your support! I will close this issue as resolved ✅

**Comment by pdiakumis** [comment]
For anyone else interested, Isofox 1.4 should be working now too. I've also updated [GRIPSS to 2.1](https://github.com/bioconda/bioconda-recipes/pull/34507).
