### ISSUE TITLE
GRIPSS - ref_genome_version HG38

### ISSUE THREAD

**Issue by stsergbg** [hartwigmedical/hmftools#301]
Hi!

Are there plans to add HG38 as a "ref_genome_version" option for GRIPSS? There is V37, V38 and HG19 for now, as far as I understand. I have many pipelines using hg38 reference with chrZZ notation. Also there is a hg38 PON file on HMF website that clearly uses chrZZ notation. Moreover, since PON files, known breakpoints and the actual genome fasta file are provided along with this option, it is not quite clear what this "ref_genome_version" option is used for.

Thank you in advance,
Sergey

**Comment by abelhj** [comment]
I had this same problem yesterday.  As far as I can tell GRIPSS is only using the reference version to determine the poly_g regions and the location of PSM2, so hopefully this is not a serious concern?

**Comment by toddajohnson** [comment]
I think that is already true, but just not explicitly stated in the README. The ref_genome_version argument to GRIPSS seems to be parsed through a common class used across the HMF programs (hmf-common/src/main/java/com/hartwig/hmftools/common/genome/refgenome/RefGenomeVersion.java).  Lines 27-38 parse the allowed strings into V37, V38, or HG19 versions, but V38 will be assigned if the ref_genome_version is one of V38, RG_38, 38, or HG38 (so, seems don't use GRCh38 or hg38).  V38 uses UCSD chromosome names (with chr prefix, chrM instead of MT), like HG19.  In my experience, the problem that occurs is when one does not pass ref_genome_version, V37 is the default, and V37 does not have the chr prefix.

**Comment by abelhj** [comment]
With gripssv2.1, '38' does not work. 'V38' apparently does.

**Comment by charlesshale** [comment]
This is a bug - there is a second place in Gripss which expects only either V37 or V38. I'll fix this for v2.2, due out in about a week.

In general as Todd pointed out, all HMF tools accept '37' or 'V37' for GRCh37 and '38' or 'V38' for GRCh38.

**Comment by charlesshale** [comment]
Gripss v2.2 has been released now with this fix:

https://github.com/hartwigmedical/hmftools/releases/tag/gripss-v2.2

**Comment by stsergbg** [comment]
So gripss now can accept HG38 as ref_genome_version ? Could you please update the README if that's the case?

**Comment by charlesshale** [comment]
All HMF tools work with GRCh37 and GRCh38. The ref_genome_version config accepts the following strings for each: 37, V37 or HG37, or 38, V38 or HG38.

The Gripps READ-ME lists the options as V37 or V38, but you can set it as HG38 if you prefer.
