### ISSUE TITLE
Compatability of Linx with other mutation callers

### ISSUE THREAD

**Issue by dominikglodzikhms** [hartwigmedical/hmftools#338]
Dear HMF Team,

thank you for creating this excellent resource which is pushing cancer research forward!

We use your tools extensively, also in combination with Sentieon and Sanger methods. As we are converging on a default workflow, I wondered about input for Linx.

[Here](https://github.com/hartwigmedical/hmftools/blob/master/linx/README.md) I notice that Linx requires a .vcf file with SVs and a folder with Purple output.
- sv_vcf (Full path and filename for the SV VCF)
- purple_dir (Directory with sample data for structural variant VCF, copy number and purity data files as written by GRIDSS and Purple.)

We wonder about the possibility of using Linx in conjunction with other SV and copy number algorithms, specifically, SVs from Sentieon's TN scope and Sanger's ASCAT. Do you have a sense whether this could be feasible? 
If yes, are there any specific requirements for file formats in the 'sv_vcf' and 'purple_dir'. 

Could you clarify which files from 'purple_dir' are required for Linx to run? 
Could you explain why Linx requires two SV .vcf files, one fed as 'sv_vcf' and one in 'purple_dir '?

Thank you very much for your help!
Dominik

**Comment by charlesshale** [comment]
Hi Dominik,

The VCF required by LInx and set in the 'sv-vcf' config is the Purple VCF, which therefore is expected to reside in the purple directory. So only one VCF for SVs is expected and loaded.

There are a number of VCF fields which Linx uses which are set upstream by Gridss, Gripss and Purple and so I don't think it's feasible to try to set these some other way.

The data required from by Linx related to copy number is quite specific to Purple:
- copy number (major and minor) per gene
- segment copy number including type of segment breakend, major/minor copy number, BAF, and depth window count
- AMP, DEL and biallelic somatic driver events
- sample purity and ploidy

The HMF pipeline can be run from BAM hours and for a typical WGS of 100x/30x is expected to run in a few hours, so might be easiest to re-run it in order to get the required input for Linx. See https://github.com/hartwigmedical/hmftools/blob/master/pipeline/README_WGS.md

thanks.
