### ISSUE TITLE
purple initialisation error

### ISSUE THREAD

**Issue by lichennan123** [hartwigmedical/hmftools#350]
Hello Hartwig team,

Thank you for making such an excellent toolkit! I successfully ran cobalt, amber, and gridss/gripss using my wgs data. However, running the latest version of PURPLE (v. 3.7.2) always threw me an error 'initialisation error, exiting'. And I did not find any details about what was going wrong. What is interesting is that an older version (v 3.1) could work without the same problem using the same set of input files (though different versions seem to require slightly different naming of input files). So I wonder if you have any idea about what this initialisation error suggests and whether you have any suggestions upon this issue. Thank you.

Sincerely,
Chennan

**Comment by charlesshale** [comment]
Hi Chennan,

Could you upload the command that you're using to call Purple?

thanks,

Charles.

**Comment by bobrad98** [comment]
> 

Hi Chennan,

I'm having the same problem as you, did you manage to find the solution?

**Comment by charlesshale** [comment]
Could you paste me the log from Purple up to when it hits the initialisation error?

There should be no need to revert to any earlier version of Purple.

What are the contents for:
/fdb/ensembl/pub/release-108/fasta/homo_sapiens/dna/

?

These should be the Hartwig Ensembl files from our resource page.

thanks.

**Comment by bobrad98** [comment]
Hi Charles,

I'm having the same problem as Chennan, so I wanted to ask you a couple of things:
1) Is [this](https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/dna_pipeline/v5_31/38/common/ensembl_data?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) the Ensembl data which should be used?
2) After digging through the code, I found that versions > 3.3 and < 3.3 differ in the IsValid method of [ReferenceData]
(https://github.com/hartwigmedical/hmftools/blob/46aa145e83f422a25412e3918d1aff7203c38c10/purple/src/main/java/com/hartwig/hmftools/purple/config/ReferenceData.java#L251):

older - public boolean isValid() { return mIsValid }
newer - public boolean isValid() { return mIsValid && TargetRegions.isValid(); }

I think this is important for this discussion because all of the older versions pass the point in the execution where Chennan and I got stuck, but all of the newer versions failed at that step.

Can you please take a look at this and see if I'm missing anything?

Thanks!

**Comment by lichennan123** [comment]
> Could you paste me the log from Purple up to when it hits the initialisation error?
> 
> There should be no need to revert to any earlier version of Purple.
> 
> What are the contents for: /fdb/ensembl/pub/release-108/fasta/homo_sapiens/dna/
> 
> ?
> 
> These should be the Hartwig Ensembl files from our resource page.
> 
> thanks.

Here you go. It does not contain useful info for debugging... 

```
10:39:34 - [INFO ] - Purple version: 3.7.2
10:39:34 - [INFO ] - output directory: /data/lic27/project_clon_evo/practice/27_linx/04_purple/
10:39:34 - [INFO ] - reference(DTB-090-N) tumor(DTB-090-PRO)
10:39:34 - [INFO ] - using ref genome: V38
10:39:34 - [ERROR] - initialisation error, exiting
```

About the ensembl data cache, I believe I wasn't able to find that in the [link](https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC) attached in the [github page](https://github.com/hartwigmedical/hmftools/blob/master/purple/README.md). Since the old version that does not require this information works for me, I am good. But can you maybe attach the path through which everyone can access the ensembl data cache for anyone who would like to use? Thank you!

Chennan

**Comment by lichennan123** [comment]
Hi Charles and Bozidar,

When I looked at my previous script used for running linx, I realized that the ensembl path came from google cloud (that is probably attached in the github page for linx, rather than for purple). When I used that on the latest version of purple, it worked nicely. I would recommend that all the relevant links to the DNA resource updated to the Google cloud so that anyone using these wonderful tools will no longer run into the same issue. Thank you!

Chennan
