### ISSUE TITLE
ecDNA links

### ISSUE THREAD

**Issue by Bo-UT** [hartwigmedical/hmftools#374]
hello, 

I have an ecDNA link and want to get the derivative chromosome. I assume the SVs are connected in the order of 1986-1982-1980-1958-1963-1969-1971, but the sequences seem are: chr7 94214606:92164825 -  94142005:92203995 - 94091392:92205026, ... The derivative chromosome looks not correct. I am very confused with lowerBreakendIsStart and upperBreakendIsStart . Could you give a guideline how to read the connection order of these SVs? 

<img width="773" alt="Screen Shot 2023-03-10 at 6 51 39 AM" src="https://user-images.githubusercontent.com/55055062/224321459-2e5acf14-b39e-4b4e-b86f-d0a6292a1012.png">

<img width="628" alt="Screen Shot 2023-03-10 at 6 55 22 AM" src="https://user-images.githubusercontent.com/55055062/224321416-52ccc72e-814e-44b9-af71-b952ddb889e6.png">

Thanks

Bo

**Comment by p-priestley** [comment]
I highly recommend that you use the visualisations in LINX to draw this cluster 
 (see https://github.com/hartwigmedical/hmftools/blob/master/linx/README_VIS.md)

Each line in the svLink table represents a link in a chain between 2 breakends.  Since each SV has a start and an end breakend, we need to record both which SV is linked in the chain and which end of that SV.   The 'IsStart' fields indicate whether it is the start or end of each SV that is joined in the link.   So in the 1st line above the end of 1986 is chained to the end of 1982.

The full chain in this example goes like this:

????- 94,214,606  <reverse direction>
<INV>
92,164,285-92,203,995 <forward direction>
<INV>
94,142,005-94,091,392  <reverse direction>
<INV>
92,205,026-92,536,647  <forward direction>
<DEL>
92,609,079-92,949,479 <reverse direction>
<INV>
93,035,563-93,098,980 <forward direction>
<INV>
93,496,620-93,496,920 <reverse direction>
<DUP>
93,312,576- ????   <forward direction>

It is an incomplete circle, but LINX has marked as an ecDNA based on the documented logic (https://github.com/hartwigmedical/hmftools/tree/master/linx#special-considerations-for-extrachromosomal-dna-ecdna) and assumes there is a missed variant which may have completed the chain.

**Comment by Bo-UT** [comment]
Thanks. 
I ploted this cluster (2605) that has ecDNA. It's really hard to read how the SVs are connected. Is there a bed file output from Linx to show the connections? Thanks

![ecDNA circos](https://user-images.githubusercontent.com/55055062/224685766-b651cee9-17ea-47b5-bcb0-83060eed330a.png)

**Comment by p-priestley** [comment]
Thanks for the visualisation.   The picture is very complicated obviously, but that is because there are thousands of variants here.  In this case, the cluster touches every chromosome in the genome, which I think is unlikely in a single event, so I do think there may be a combination of over clustering and perhaps some FP SV calls here?

The  high copy number is (just) visible on chr7.   If you wanted to have a closer look, I would suggest looking at the purple somatic copy number to see where the exact bounds of these high copy number regions are.    There is no way in LINX currently of only visualising the predicted ecDNA part of a cluster.
