### ISSUE TITLE
Regarding templated insertions in LINX

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#390]
Hi,

Regarding the templated insertion model in Linx. In the output file *.svs.tsv I can find the TI count in the start and end topology groups. 
Do these TI counts include both templated insertions from other chromosomes (via translocations) and inserted repeated elements (via single breakends)?
Is there a way to figure out from the LINX output if a specific breakpoint is part of a templated insertion?

Thanks,
Jose

**Comment by charlesshale** [comment]
Linx groups SV breakends into local topology groups as described in the documentation. Any linked/chained breakends (aka templated insertions) falling into the same local topology group are counted towards the localTICountStart/End values you've referred to. These can include SVs which link 2 chromosomes.

SVs which have been chained together have these chain links written to the LINX links file, eg SAMPLE_ID.linx.links.tsv. Since linked breakends will often span local topology groups, looking into the links.tsv file gives the complete picture of all templated insertions. So to answers your question, each SV breakend in the links file is part of a templated insertion.

Separate from this, the insert sequences which some SVs and single breakends have are not counted as links / templated insertions, even though in reality they may be of a similar nature (though too short to be mapped). They do not feature in the local topology group TI counts nor in the links TSV file.
