### ISSUE TITLE
Is it possible to have PURPLE report any germline missense variants in a selected gene(s)?

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#406]
I am analyzing a cohort in which some samples are likely a rare kidney cancer known to be caused by germline nonsense or missense mutations in the FH gene followed by second hits or LOH.  I was thinking that the reportGermlineVariant=VARIANT_NOT_LOST setting in the gene panel would allow biallelic missense variants to be reported, but only one sample with a nonsense germline was reported, leaving three samples with biallelic missense SNVs "hidden", since the specific variants are not in the 2020 version of ClinVar that is in the HMF resource files.  One of the three has a matching entry in the latest ClinVar, so I could update the underlying resource, but still, two have imperfect ClinVar matches (Likely pathogenic entries with matching POS but not alleles, or matching amino acid change, but for a different genomic position), so should still be missed.

Is there any way to have PURPLE report not just variants that are labelled "Pathogenic" based on ClinVar, but any biallelic missense variants in a selected gene(s)?  I have been looking through the driver catalog code, but it seems like ClinVar based PATH filtering is going to always remove those SNVs.

By the way, is there a reason that ClinVar in the latest 5.32 resource file is the version from 2020?  There are now three times as many entries as back then.

**Comment by charlesshale** [comment]
Will discuss your question about biallelic annotations.

We intend to update Clinvar for the next pipeline release (v5.33), so about a month

From: "Todd A. Johnson" ***@***.***>
Reply to: hartwigmedical/hmftools ***@***.***>
Date: Monday, 29 May 2023 at 5:55 pm
To: hartwigmedical/hmftools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hartwigmedical/hmftools] Is it possible to have PURPLE report any germline missense variants in a selected gene(s)? (Issue #406)


I am analyzing a cohort in which some samples are likely a rare kidney cancer known to be caused by germline nonsense or missense mutations in the FH gene followed by second hits or LOH. I was thinking that the reportGermlineVariant=VARIANT_NOT_LOST setting in the gene panel would allow biallelic missense variants to be reported, but only one sample with a nonsense germline was reported, leaving three samples with biallelic missense SNVs "hidden", since the specific variants are not in the 2020 version of ClinVar that is in the HMF resource files. One of the three has a matching entry in the latest ClinVar, so I could update the underlying resource, but still, two have imperfect ClinVar matches (Likely pathogenic entries with matching POS but not alleles, or matching amino acid change, but for a different genomic position), so should still be missed.

Is there any way to have PURPLE report not just variants that are labelled "Pathogenic" based on ClinVar, but any biallelic missense variants in a selected gene(s)? I have been looking through the driver catalog code, but it seems like ClinVar based PATH filtering is going to always remove those SNVs.

By the way, is there a reason that ClinVar in the latest 5.32 resource file is the version from 2020? There are now three times as many entries as back then.

**Comment by p-priestley** [comment]
Clinvar has been update in v5.33

No plans to change germline reporting logic at this stage sorry.
