### ISSUE TITLE
 [WARN ] - sample(tumor-id) missing viral annotations file

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#430]
I am running CUPPA (v1.8) with the warning: [WARN ] - sample(tumor-id) missing viral annotations file: /path/to/linx/tumor-id.virus.annotated.tsv 

CUPPA will look up the viral annotations file in linxDataDir:
https://github.com/hartwigmedical/hmftools/blob/2f15ed662f5f308a25e5694bb552fb15d1abb4a7/cuppa/src/main/java/com/hartwig/hmftools/cup/feature/FeatureDataLoader.java#L111

Should the viral annotations file in virusbreakend directory but not the linx directory?

**Comment by p-priestley** [comment]
Thanks for your multiple bug reports - we will look at these shortly.  

Since you are using multiple different tools, I would be interested to understand your use case and which institution it is for so we can give better advice.  Perhaps you could email me at  p.priestley@hartwigmedicalfoundation.nl if you would like to discuss.

**Comment by charlesshale** [comment]
The virus interpreter needs to be moved into the Linx directory, otherwise use the config 'sample_data_dir' and put all applicable sample pipeline output files in there.
