### ISSUE TITLE
Driver Catalog File missing

### ISSUE THREAD

**Issue by zhaowsong** [hartwigmedical/hmftools#556]
Hi authors,

Thank you for developing and maintaining these tools. I recently used the HMF pipeline to run some samples, but Purple did not output the TUMOR.driver.catalog.somatic.tsv file. Below is the specific code I ran.
<img width="768" alt="image" src="https://github.com/hartwigmedical/hmftools/assets/116059475/13c2635a-7052-434b-a230-a9e1514936a1">

Additionally, I have some questions regarding gene amplification. HMF's standard for gene amplification is "Report amplification if min gene copy number > 3x sample ploidy and partial amplification if max gene copy number > 3x sample ploidy." Isn't this standard too strict? Below are the gene copy number results output by Purple. Generally, isn't a copy number greater than 2 considered a gain? Higher copy numbers, such as greater than 4, could be considered amplification.
<img width="729" alt="image" src="https://github.com/hartwigmedical/hmftools/assets/116059475/590c24f4-b3dd-4d9b-a5d6-82764393e0b7">

**Comment by p-priestley** [comment]
We have taken a conservative approach to mark amplificaiton drivers, restricting it to 3x ploidy and to the defined list of cancer genes in the driver panel.   We found a relative gain seems to be more informative than an absolute gain which is why we express it in terms of ploidy.    Certainly lower amplifications (for example whole arm gains) are highly recurrent in certain cancer types and may be cancer relevant, but these are not necessarily associated with a specific gene, and so we have restricted to high confidence drivers for the purposes of the driver catalog.  

In the gene copy number file above, the copy number of ALL genes is shown for each sample, so you can extract lower level amplifications from there.  

My colleague will reply on why PURPLE might not have output a driver catalog file

**Comment by charlesshale** [comment]
Could you show me the log file produced by Purple? The drivers are written last and if it failed for example to produce the plots, it would have stopped before getting to this step.

**Comment by zhaowsong** [comment]
Thank you for your response and the explanation regarding the copy number. I think I have found the reason why the Driver Catalog File was missing—I missed the -run_drivers parameter. Everything is outputting correctly now.
