### ISSUE TITLE
Plotting Raw Copy-Number Results

### ISSUE THREAD

**Issue by seedgeorge** [hartwigmedical/hmftools#579]
Hi there, firstly, congratulations on the excellent toolkit. I've run a test case using the COLO829 sample set. 

If I wanted to plot some copy-number plots manually, using HMF-generated copy ratio and BAF data, am I right in thinking that:
- The COBALT output for per-bin copy-ratios (COLO829v003T.cobalt.ratio.tsv) contains the data I need - am I right in performing the following calculation to get appropriately corrected log2ratios? log2(exp(ratios1$tumorGCRatio)/exp(ratios1$referenceGCRatio))
- I’m currently filtering out rows based on: referenceReadDepth == 0, tumorGCRatio == -1  - it makes the plots smoother. Is this ok?
- The AMBER output (COLO829v003T.amber.baf.tsv) has the BAF data, and I can use the tumorBAF column if I want mirrored BAFs splitting away from 0.5, or tumorModifiedBAF if I want unmirrored.
- Also, I’d like to plot the segments over these, presumably using the data found in COLO829v003T.purple.cnv.somatic.tsv - but no copy-ratio data is retained for this output file, so I’m not sure how to do that. I have to say it's strange to have a BAF column, but no Log2Ratio column - I think this runs against convention for copy-number segment output files.
- One final note: I think linear plots of CNA data are more useful than circularised plots, and make for easier cross-sample comparisons.

**Comment by p-priestley** [comment]
If you want to plot raw segmented data manually, I would suggest using the segment.tsv file produced by PURPLE.   This merges all data from AMBER, COBALT and SV inputs and creates the raw segmentation for the copy number fit.   The input.png file produced by PURPLE is already a figure which shows this data.

To answer your sepcific question:
• The ratios from cobalt are already in natural space, so you don't need to use exp().  I also don't recommend correct tumor with normal so I would just use log2(tumorGCRatio) if I was you.
• TumorGCRatio==-1 means that row is masked, so it absolutely should be excluded.   referenceReadDepth = 0 means no reads found in reference.  This may be a germline homozygous deletion or something unmappable.
• That is correct for AMBER
• The values in the cnv.somatic.tsv are the final purity adjusted copy number values.   I agree that the BAF column is unnecessary since we also have minor and major allele copy number.   You can ignore.
• We use circular plots so that we can include structural variants in a natural way (see the circos.png or the LINX plots). For the input.png plots i can understand linear may be more convenient, but we use these for QC purposes only.

**Comment by seedgeorge** [comment]
Thanks! This is informative. My understanding is that the `.purple.segment.tsv` are the segment values before final smoothing and assignment by PURPLE (ie. an intermediate data set), but I would like to plot the input data points for Log2ratio and BAF, and then overlay the **final** calls over the top. I'm hesitant to use the intermediate file for this (it seems very noisy?) and would rather use the final assigned segments (from `purple.cnv.somatic.tsv`) instead, as these look (for the most part) plausible.

| but we use these for QC purposes only
I (and other users) will probably enjoy to do the same :)

Another specific question: reviewing the copy number data from COLO829, I note some segments with a bafCount of 0 but an assigned value in the baf column - is this a dummy or default value? In some cases it is implausible (a BAF of 1 in a segment with estimated copyNumber of 0). For example, the segment 
chr16 | 58590642 | 58629426 
Has a `copyNumber` of -0.01, `bafCount` of 0 and `observedBAF` of 0, but the method to call it is apparently `BAF_WEIGHTED` - seems strange.

**Comment by p-priestley** [comment]
Re the BAF_WEIGHTED, I checked this case.   There are indeed no BAF points in this region.   BAF_WEIGHTED means the average of all depth windows for the region (weighted by BAF) but since there are no BAF points in this region, it simply uses the raw average copy number of this region.

**Comment by seedgeorge** [comment]
Ok, interesting. So are the following conclusions correct:

- This is a segment supported by an SV (visible in linx) and it covered 38 depthWindow areas for ratio calculation, for which very very few reads are mapped (read depth ratios of ~0.3, tumorGCRatio of 0.0027)
- The Linx JCN is ~2, is that an estimate of the number of copies of this event?
- No BAF points are within this small area so cannot be used to infer.
- Therefore this is a homozygous deletion?

**Comment by p-priestley** [comment]
Yes that would be my interpretation. This appears to be a local homozgous deletion of ~38kb. The region has subsequently been duplicated giving a JCN of 2.
