### ISSUE TITLE
LINX Low Copy Number Accuracy

### ISSUE THREAD

**Issue by amarinderthind** [hartwigmedical/hmftools#601]
In recent [benchmarking](https://www.nature.com/articles/s41467-023-41259-w), LINX had low copy number performance on a COLO829 cell line data set.

> Ambigram yields a copy number difference of seven from ground truth, while LINX produced 29
Did the Ambigram developers use LINX correctly? If so, do any recent versions of LINX improve performance for this scenario?

**Comment by p-priestley** [comment]
Thanks for the reference.   I had not seen this.   I am not familar with that paper, but it appears that the purity and ploidy fit conducted by the authors for their COLO829T analysis yielded the wrong ploidy (for both PURPLE-LINX + other tools).   This is a bit suprising to me as we regression test every release on COLO829T.   The dowsntream impact of this is that incorrect copy numbers may be inferred.  For example if you fit with much lower purity, amplifications will appear to have much higher absolute copy number.     The paper claims that since the copy number is not matching that the LINX result should be dismissed, but I think that is only an artefact of the poor purity fit here. 

Supp figure 12 of this publication does appear to produce a faithful reconstruction of LINX's resolution of the chaining and I think that is the only plausible chaining.   I cannot see how separate BFB on chr3 and chr6 which are later fused  as proposed by the ambigram authors can explain the pattern.    For example, only ~400 bases of chr6 are actually amplified so how could this occure from  an arm level event as claimed?   

In this publication we provide a video reconstruction of our proposed model of the BFB history of chr 3 in COLO829: https://www.sciencedirect.com/science/article/pii/S2666979X22000726

**Comment by amarinderthind** [comment]
Thanks for the explanation. Much appreciated.
