### ISSUE TITLE
help to interpret results from PURPLE, Delly problem

### ISSUE THREAD

**Issue by a00101** [hartwigmedical/hmftools#64]
First thank you for developing this nice tools.

I've been in trouble with interpretation of results from PURPLE.
I got results below.

<Sample.purple.cnv.gene.tsv>

gene | minCopyNumber | maxCopyNumber
SRY | -1.6912 | -1.6912
RPS4Y1 | -1.6912 | -1.6912
ZFY | -1.6912 | -1.6912
.......
HOOK1 | 6.1105 | 6.1105
CYP2J2 | 6.1105 | 6.1105
C1orf87 | 6.1105 | 6.1105

In this case, can we assume that deletion occurred in SRY and 3 copies of amplification in HOOK1?

I don't know how to set the cutoff.

One more thing, I used delly to detect structural variation, can I use it with GRIDSS as substitute? How do you fix the results if you shouldn't?

please help me.

**Comment by p-priestley** [comment]
The gene copy number file is described here: https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#gene-copy-number-file

Since copy  number changes can occur within gene boundaries we report the minimum and maximum number of chromosomal copies observed at any base in the exons of the gene.      In your example,they are all the same numbers

PURPLE does not round the copy number output or cap copy number at 0 as this is left to the downstream application.    Clearly there are not negative copies of any genes so the SRY, RPS4Y1 and ZFY copy numbers are wrong here.    This could be due to a number of reasons: possibly due to GC bias in your sample leading to a poor local copy number calculation in this region, or potentially that the purity or ploidy fit overall is poor.   You can check the QC plots to try and work this out.   If you share the QC plots I can give you some thoughts.
