### ISSUE TITLE
QC Fail_Segment and Fail_Deleted_Genes

### ISSUE THREAD

**Issue by DDWeijers** [hartwigmedical/hmftools#84]
Hi,

I am looking for some help and information on QC results that were outputted by PURPLE. We have been running PURPLE on several tumor-normal combinations, among others to determine the tumor purity in the samples. For two combinations, the tumor purity was much lower than I would have expected from the distribution of allele frequencies of somatic variants. Their QC shows Fail_Segment for one combination and Fail_Deleted_Genes for the other. 

The combination with Fail_Segment contains a tumor with over 200,000 somatic SNVs that shows a high level of segmentation in a copy number plot we made previously as well. I think the large number of mutations may be related to the large numbers of segments and I was wondering whether you know of a way to deal with that. 

The other combination flagged as Fail_Deleted_genes, supposedly has 655 deleted genes. As I don't really understand where the deleted genes causing such a fail come from, could you tell me a bit more about them? Would they be in the germline, in the tumor or in both? Is there a list with those genes available, so I can see what happened? I didn't see any problems or remarkable results with this sample before, tumor load was in line with what was expected and copy number plots looked normal (for a tumor, that is). 

If you need any additional information, please let me know and I'll try to provide what I can within the privacy limits. 
Thanks a lot!
Best,
Dilys

**Comment by p-priestley** [comment]
Hi Dilys,

The FAIL reasons are described here:

https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#9-determine-a-qc-status-for-the-tumor

We generally observe both of these issues in samples with large scale GC bias.  Whilst we adjust for GC bias on a local level - MB scale GC bias is very difficult to adjust for and can cause significant noise in copy number output   

FAIL_SEGMENT simply means that we have many copy number breakpoints unsupported by SV even after our extensive smoothing.  We fail these samples as it causes risk for us to detect FP homozygous deletions and amplifications, and potentially miss SNV in high GC regions (eg. TERT promoters).   Our QC cutoff is relatively aggressive though so the sample may still be ok.  

FAIL_DELETED_GENES simply counts the # of homozygously deleted genes in the tumor.  If there are too many, then it is deemed biologically implausible.  This affects about 0.25% of our samples and we see 1 of 2 scenarios - high GC content chromosomes such as chr19 are called as homozygously deleted (for samples with high GC bias)  OR  chr X is called as homozygously deleted (likely in cases of germline mosaic X which PURPLE doesn't properly handle).    Again we QC fail as a precaution so that we don't report homozgously deleted genes.   You can see a list of genes that are homozygously deleted by looking for genes with minCopyNumber < 0.5 in the gene copynumber output.

If you are fine to attach the PURPLE circos.png and input.png output or send privately to me p.priestley@hartwigmedicalfoundation.nl then I can give you a better diagnosis of what might be causing this in your sample and what you can do.

Peter
