### ISSUE TITLE
PURPLE Driver Analysis in Highly Polymorphic Genome Regions

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#87]
I see the MHC region regularly appearing in the driver catalog TSV. Could it be an artefact of alt contigs?

![driverAnalysis](https://user-images.githubusercontent.com/631218/82420924-b4275c00-9ac3-11ea-990f-407a787f3de4.png)

It seems each of the three MHC Class I genes have wild read depth fluctuations, probably due to different segments mapping better to the reference chr6 and other segments to an alternative of it.

**Comment by p-priestley** [comment]
Hi Dario, 

We noticed this problem a while back.  It occurred due to us generating our GC_profile.1000bp.cnp for hg38 off the full ref genome which meant that a 2M base portion of the genome was deemed unmappable around HLA.    We fixed this a while back by generating it off the no_alt_analysis genome.     Could you make sure you are using our latest GC_profile.1000bp.cnp  file please?   

Also if you are using the full 38 genome, you need to make sure your aligner is set to alt aware (BWA is by default I believe).

Peter

**Comment by DarioS** [comment]
It is resolved by updating to the current CNP file.
